<?php
return [
    "dcode" => "Welcome to our website! We offer a variety of divination services, including tarot readings, poetry interpretations, and astrology introductions. Our tarot readings can help you explore your inner world, solve problems, and predict the future. Poetry interpretations provide insights and guidance to lead you towards a better life path. Astrology introductions allow you to gain a deeper understanding of yourself and those around you, enhancing self-awareness and interpersonal relationships. DCode will provide accurate answers and advice based on the questions and birth information you provide. Please browse our website and begin your mystical journey!",
    "tarot_list" => "We offer free Tarot card readings for various aspects of life, whether it's love, work, or career, you can find answers here. Tarot card reading is an ancient divination method that uses a deck of 78 cards. Through the symbolic meanings and arrangement of Tarot cards, the reader can explore their inner self and the possibilities of the future, as well as understand the significance of surrounding events. Tarot card reading is considered a tool for spiritual exploration, helping individuals gain insights and guidance to navigate their lives. It's a highly popular divination method, utilized in modern psychology, spiritual therapy, creative arts, and spiritual exploration fields.",
    "tarot_one" => "Single Card Divination - Provides concise and straightforward messages; this type of divination is helpful when more specific answers are needed. Focus on your question. Choose a card. The card will answer your question. Answers can be obtained for love, work, and finances.",
    "tarot_showall" => "Tarot card reading is an ancient divination art that reveals information about the past, present, and future through the interpretation of tarot card images and symbols. Our website features a variety of tarot card reading themes, including love, career, finances, and life purpose. Whether you are new to tarot or already have some knowledge, our readings will provide you with answers in a professional and accurate manner.",
    "three_cards" => "Holy Triangle Divination Method - Provides explanations and predictions for the issue, greatly helping in understanding the situation and estimating future developments.",
    "four_cards" => "Four-Card Spread - Four cards provide the following insights: known issues, unknown issues, the problem area, and how to solve it.",
    "four_element" => "Four Elements Spread - Fire: How to take action in facing the issue. Air: Understanding the issue, including negative aspects. Water: Emotional development and the impact on those involved. Earth: Practical considerations and material resources related to the issue.",
    "six_pointed_star" => "Hexagram Spread - The hexagram is also known as the Star of David, Solomon's Star, Solomon's Seal, Hebrew Star, Jewish Star, and more. It is a versatile spread suitable for \"any question.\"",
    "friendship" => "Friendship Spread - This spread requires six cards, each representing different aspects of the friendship: the other person's character, how you interact, potential challenges in the friendship, the outlook of your friendship, and so on. Each card has a different meaning and should be carefully interpreted in relation to the question to gain a deep understanding of the emotional state between you and your friend, and how to improve or strengthen the friendship.",
    "week" => "Weekly Horoscope Spread - The order of interpretation does not necessarily have to follow the days of the week, but can be broadly applied to the overall horoscope explanation. Some basic knowledge of astrology is necessary for this.",
    "either" => "When faced with a choice between two options, the most commonly used divination method is the Two-Choice Spread. For example: Should you choose Person A or Person B? Should you continue your education or start working? For decision-making questions like these, it can provide very good advice and answers.",
    "public_tarot" => "The public tarot reading website offers various tarot card divination services, including love, financial fortune, career, health, and future predictions, helping people answer various questions and dilemmas. Using the website for divination is very simple: just choose the type you're interested in, concentrate on your question, and click to draw a card to get your tarot reading result. The public tarot reading website not only provides interpretations of various divination results but also offers detailed introductions to the tarot cards and their historical and cultural backgrounds, allowing you to gain a deeper understanding of the mysteries of tarot cards.",
];
